w4d2/ninetyninecats/config/routes.rb
Rails.application.routes.draw do
  resources :cats, only: [:index, :show, :create, :new, :update, :edit]
  resources :cat_rental_requests, only: [:index, 
                                  :show, :create, :new, :update, :edit]

end

w4d2/ninetyninecats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :datetime         not null
#  color       :string(255)
#  name        :string(255)      not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Cat < ActiveRecord::Base
  COLORS = %w{black white brown tabby}
  
  validates :color, inclusion: { in: COLORS,
     message: "%{value} is not a valid color" }
  validates :sex, inclusion: { in: %w(M F),
    message:  "Sex must be M or F" }
  validates :birth_date, :name, :sex, :color, presence: true 
  validates :birth_date, :timeliness => 
  {:on_or_before => :now, :type => :date}
  
  has_many(
    :cat_rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy
  )
  
  def age
    Time.now - :birth_date
  end
  

  
end

w4d2/ninetyninecats/app/models/cat_rental_request.rb
# t.integer :cat_id, null: false
# t.datetime :start_date, null: false
# t.datetime :end_date, null: false
# t.string :status, default: "PENDING"


class CatRentalRequest < ActiveRecord::Base
  
  
  validates :status, inclusion: {in: %w(PENDING APPROVED DENIED), 
    message: "Status must be PENDING, APPROVED, or DENIED"}
  validates :cat_id, :start_date, :end_date, presence: true
  validate :status, :overlapping_approved_requests
  validates :end_date, :timeliness => 
  {:after => :start_date, :type => :date}

  belongs_to(
    :cat,
    class_name: 'Cat',
    foreign_key: :cat_id,
    primary_key: :id
  )
  
  def approve!
    CatRentalRequest.transaction do
      self.status = 'APPROVED'
      self.save!
      overlapping_pending_requests.each do |request| 
        request.deny!
      end
    end
  end
  
  def deny!
    request.status = 'DENIED'
    request.save!
  end
    
  private 

  def overlapping_requests
    CatRentalRequest
    .where('start_date BETWEEN ? AND ?', self.start_date, self.end_date)
    .where('end_date BETWEEN ? AND ?', self.start_date, self.end_date)
    .where('cat_id = ?',  self.cat_id)
  end

  def overlapping_approved_requests
    if overlapping_requests.any?{ |request| request.status = 'APPROVED' }
      errors[:status] << "There are overlapping requests"
    end
  end
  
  def overlapping_pending_requests
    overlapping_requests.where('status = ?', 'PENDING')
  end  
  

end

w4d2/ninetyninecats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  
end

w4d2/ninetyninecats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  
  def new
    @cat_rental_request = CatRentalRequest.new
    render :new
  end
  
  def show
    @cat_rental_request = CatRentalRequest.find(params[:id])
    render :show
  end
  
  def create
    @cat_rental_request = CatRentalRequest.new(rental_params)
    if @cat_rental_request.save
      redirect_to cat_rental_request_url(@cat_rental_request)
    else
      render :new
    end
  end
  
  def edit
    @cat_rental_request = CatRentalRequest.find(params[:id])
    render :edit
  end
  
  def update
    @cat_rental_request = CatRentalRequest.find(params[:id])
    if @cat_rental_request.update(rental_params)
      redirect_to cat_rental_request_url(@cat_rental_request)
    else
      render :edit
    end
  end
  
  protected
  
  def rental_params
    params[:cat_rental_request].permit(:cat_id,:start_date, :end_date, :status)
  end
end

w4d2/ninetyninecats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  
  def index
    @cats = Cat.all
    render :index
  end
  
  def show
    @cat = Cat.find(params[:id])
    render :show 
  end
  
  def new
    @cat = Cat.new
    render :new, cat: @cat
  end
  
  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end
  
  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end
  
  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end
  
  protected
  def cat_params
    params[:cat].permit(:name, :sex, :color, :birth_date, :description)
  end
  
end

w4d2/ninetyninecats/app/helpers/application_helper.rb
module ApplicationHelper
end

w4d2/ninetyninecats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

w4d2/ninetyninecats/app/helpers/cats_helper.rb
module CatsHelper
end

w4d2/ninetyninecats/app/views/cat_rental_requests/_form.html.erb
<% form_type = (cat_rental_request.persisted? ? "PATCH" : "POST") %>
<% form_action = (cat_rental_request.persisted? ? cat_rental_request_url(cat_rental_request) : "/cat_rental_requests") %>
<% submit_field = (cat_rental_request.persisted? ? "Update cat rental request" : "Save cat rental request") %>


<form action="<%= form_action %>" method="POST">
  <input type="hidden" name="_method" value=<%= form_type %>>
  
  <select name="cat_rental_request[cat_id]" id="cat_rental_requests_cat_id">
    <option value="">Blank</option>
    <% Cat.all.each do |cat| %>
    <option value="<%= cat.id %>"  <%= "selected" if cat_rental_request.cat_id == cat.id %>>
    <%= cat.name %>
    </option>
    <% end %>
  </select>
  <br>
  
  <input type="date" name="cat_rental_request[start_date]" value=<%= cat_rental_request.start_date %>>
  <br>
  
  <input type="date" name="cat_rental_request[end_date]" value=<%= cat_rental_request.end_date %>>
  <br>
  
  <input type="submit" value=<%= submit_field %>>  
</form>

w4d2/ninetyninecats/app/views/cat_rental_requests/edit.html.erb
<h1>Edit Rental Request</h1>

<%= render "form", cat_rental_request: @cat_rental_request %>

w4d2/ninetyninecats/app/views/cat_rental_requests/new.html.erb
<h1>Rental Requests</h1>

<%= render "form", cat_rental_request: @cat_rental_request %>

w4d2/ninetyninecats/app/views/cat_rental_requests/show.html.erb
<h1>A Cat Rental Request</h1>

<table>
  <tr>
  <td>Cat: <%= @cat_rental_request.cat.name  %></td>
  <td>Start Date: <%= @cat_rental_request.start_date  %></td>
  <td>End Date: <%= @cat_rental_request.end_date  %></td>
  <td>Status: <%= @cat_rental_request.status  %></td>
  </tr>
</table>

w4d2/ninetyninecats/app/views/cats/_form.html.erb
<% form_type = (cat.persisted? ? "PATCH" : "POST") %>
<% form_action = (cat.persisted? ? cat_url(cat) : "/cats") %>
<% submit_field = (cat.persisted? ? "Update your cat" : "Save your cat") %>


<form action="<%= form_action %>" method="POST">
  <input type="hidden" name="_method" value=<%= form_type %>>

  <input type="text" name="cat[name]" value="<%= cat.name %>">
  <br>
  
  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" <%= "checked" if cat.sex == 'F' %>>
  <label for="cat_sex_female">Female</label>
  <br>
  
  <input type="radio" name="cat[sex]" id="cat_for_male" value="M" <%= "checked" if cat.sex == 'M' %>> 
  <label for="cat_sex_male">Male</label>
   <br>
  
  <select name="cat[color]" id="cat_color">
    <option value="">Blank</option>
    <%= Cat::COLORS.each do |color| %>
      <option value="<%= color %>" <%= "selected" if cat.color == color %>>
        <%= color.capitalize %></option>
    <% end %>
  </select>
  <br>
  
  <input type="date" name="cat[birth_date]" value=<%= cat.birth_date %>>
  <br>
  <textarea rows="3" cols="50" name="cat[description]" placeholder="Tell us about cat" id="cat_description"><%= cat.description %></textarea> 
  <br>
  
  <input type="submit" value=<%= submit_field %>>  
</form>

w4d2/ninetyninecats/app/views/cats/edit.html.erb
<%= render "form", cat: @cat %>

w4d2/ninetyninecats/app/views/cats/index.html.erb
<h1>
  All the Cats
</h1>

<ul>
  <% @cats.each do |cat| %>
  <li> <a href="<%= url_for(cat)%>"><%= cat.name %></a>
  <% end %>
</ul>

w4d2/ninetyninecats/app/views/cats/new.html.erb
<%= render "form", cat: @cat %>

w4d2/ninetyninecats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <% @cat.attributes.each do |key, val| %>
  <tr>
  <td><%= key %>: </td>
  <td><%= val %></td>
  </tr>
  <% end %>
  <tr><td></td></tr>
  <% @cat.cat_rental_requests.order("start_date").each_with_index do |request,i| %>
  <tr>
    <td><%= i+1 %></td>
    <td>Start Date: <%= request.start_date  %></td>
    <td>End Date: <%= request.end_date  %></td>
    <td>Status: <%= request.status  %></td>
    
    <% if request.status == 'PENDING' %>
    <td><%= button_to "Deny", cat_rental_requests_url , method: :post %></td>
    <td><%= button_to "Approve", cat_rental_requests_url , method: :post %></td>
    <% end %>
  </tr>
  <% end %>
</table>