w5d1/Goal-App/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :goals, except: [:index, :show]
  resources :comments, only: [:destroy, :create, :new]
end

w5d1/Goal-App/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  body             :string(255)      not null
#  user_id          :integer          not null
#  commentable_id   :integer
#  commentable_type :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

class Comment < ActiveRecord::Base
  validates :body, :commentable, presence: true
  belongs_to :commentable, polymorphic: true
  belongs_to :author, class_name: "User", foreign_key: :author_id
end

w5d1/Goal-App/app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern
  included do
    has_many(
      :comments,
      as: :commentable,
      dependent: :destroy
    )
  end
end

w5d1/Goal-App/app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  body       :string(255)      not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  privacy    :string(255)      not null
#

class Goal < ActiveRecord::Base
  include Commentable
  validates :body, :user_id, presence: true
  belongs_to :user
  has_many :comments, as: :commentable
end

w5d1/Goal-App/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  include Commentable
  attr_accessor :password
  validates :username, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  before_validation :ensure_session_token
  
  has_many :goals
  has_many :comments, as: :commentable
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end
  
  def reset_session_token!
    self.session_token = ensure_session_token
    save!
    self.session_token
  end
  
  def ensure_session_token
    self.session_token = generate_session_token
  end
  
  def generate_session_token
    SecureRandom.base64(16)
  end
  
end

w5d1/Goal-App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?
  
  def current_user
    User.find_by(session_token: session[:session_token])
  end
  
  def signed_in?
    !!current_user
  end
  
  def login(user)
    session[:session_token] = user.reset_session_token!
  end
end

w5d1/Goal-App/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    render :new
  end
  
  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    flash[:errors] = @comment.errors.full_messages unless @comment.save
    if @comment.commentable.is_a?(Goal)
      redirect_to user_url(@comment.commentable.user)
    else
      redirect_to user_url(@comment.commentable)
    end
  end
  
  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end

end

w5d1/Goal-App/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
    render :new
  end
  
  def create
    @goal = current_user.goals.new(goal_params)
    
    flash[:errors] = @goal.errors.full_messages unless @goal.save         
    redirect_to user_url(current_user)
  end
  
  def edit
    @goal  = Goal.find(params[:id])
    render :edit
  end
  
  def update
    @goal = Goal.find(params[:id])
    
    if @goal.update(goal_params)
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    Goal.find(params[:id]).destroy
    redirect_to user_url(current_user)
  end
  
  def goal_params
    params.require(:goal).permit(:body, :privacy)
  end
end

w5d1/Goal-App/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.find_by_credentials(
      params[:session][:username],
      params[:session][:password]
    )
    
    if @user
      login(@user)  
      redirect_to user_url @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
  
  
end

w5d1/Goal-App/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:session_token] = @user.reset_session_token!
      redirect_to user_url @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    render :show
  end
  
  def index
    @user = current_user
    render :index
  end
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

w5d1/Goal-App/app/helpers/application_helper.rb
module ApplicationHelper
end

w5d1/Goal-App/app/helpers/comments_helper.rb
module CommentsHelper
end

w5d1/Goal-App/app/helpers/goals_helper.rb
module GoalsHelper
end

w5d1/Goal-App/app/helpers/sessions_helper.rb
module SessionsHelper
end

w5d1/Goal-App/app/helpers/users_helper.rb
module UsersHelper
end

w5d1/Goal-App/app/views/users/index.html.erb
<h1> Team Index Page </h1>

w5d1/Goal-App/app/views/users/new.html.erb
<h1> New user </h1>
<form action="<%= users_url %>" method="POST">
  <%= render "layouts/form" %>
  
  <label for='username'>username</label>
  <input id='username' type='text' name='user[username]' value='<%= @user.username %>'><br>
  
  <label for='password'>password</label>
  <input id='password' type='password' name='user[password]'><br>
  
  <input type="submit" value='Create User'>
  
</form>

w5d1/Goal-App/app/views/users/show.html.erb
<ul class="goal-list">
  <% @user.goals.each do |goal| %>
    <% if @user == current_user || goal.privacy == 'public' %>
      <li class="goal-item"><%= goal.body %>
        <% if signed_in? && @user.id == current_user.id %>
          <%= button_to("Edit Goal", edit_goal_url(goal), method: :get) %>
          <%= button_to("Delete Goal", goal_url(goal), method: :delete) %>
        <% end  %>
        <% if signed_in? %>
          <%= render 'comments/comment_form', parent: goal %>
        <% end %>
        <ul>
          <% goal.comments.each do |comment| %>
            <li><%= comment.author.username %>: <%= comment.body %></li>
          <% end %>
        </ul>
      </li>
    <% end %>
  <% end %>
</ul>
<% if signed_in? && @user.id == current_user.id %>
  <%= button_to "Create Goal", new_goal_url, method: :get %>
<% end %>

<% if signed_in? %>
  <%= render 'comments/comment_form', parent: @user %>
<% end %>

<ul>
  <% @user.comments.each do |comment| %>
    <li><%= comment.author.username %>: <%= comment.body %></li>
  <% end %>
</ul>