w4d4/MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource 	:session, only: [:new, :create, :destroy]

  resources :bands do
  	resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
  		resources :tracks, only: :new
  end

  resources :tracks, except: [:new, :index] do
  	resources :notes, only: :new
  end

  resources :notes, except: [:new, :index]

end

w4d4/MusicApp/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  bonus      :boolean          default(FALSE)
#  lyrics     :text
#  album_id   :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Track < ActiveRecord::Base
	validates :title, :album_id, presence: true

	belongs_to(
		:album,
		class_name: 'Album',
		foreign_key: :album_id,
		primary_key: :id
	)

	has_one(
		:band,
		through: :album,
		source: :band
	)

	has_many(
		:notes,
		class_name: 'Note',
		foreign_key: :track_id,
		primary_key: :id,
		dependent: :destroy
	)
end

w4d4/MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

	before_action :require_login
	
	def show
		@track = Track.find(params[:id])
		render :show
	end

	def new
		@track = Track.new
		render :new
	end

	def create
		@track = Track.new(track_params)
		if @track.save!
			redirect_to track_url(@track)
		else
			render :new
		end
	end

	def edit
		@track = Track.find(params[:id])
		render :edit
	end

	def update
		@track = Track.find(params[:id])
		if @track.update(track_params)
			redirect_to track_url(@track)
		else
			flash.now[:errors] = @track.errors.full_messages
			render :edit
		end
	end

	def destroy
		track_to_destroy = Track.find(params[:id])
		album = track_to_destroy.album
		track_to_destroy.destroy
		redirect_to album_url(album)
	end

	protected
	def track_params
		params.require(:track).permit(:title, :album_id, :lyrics, :bonus, :track_number)
	end
end

w4d4/MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
	def ugly_lyrics(lyrics)
		output_string = ''
		lyrics.each_line do |line|
			output_string << ' &#9835; ' + line
		end
		output_string
	end
end

w4d4/MusicApp/app/views/tracks/_form.html.erb
<% method = (track.persisted? ? 'PATCH' : 'POST') %>
<% action = (track.persisted? ? track_url(track) : tracks_url) %>
<% text = (track.persisted? ? 'Update' : 'Create') %>

<h1><%= text %> Track</h1>

<form action="<%= action %>" method='POST'>
<input type='hidden' name='_method' value='<%= method %>'>
<input type="hidden"
       name="authenticity_token"
       value="<%= form_authenticity_token %>">

<label for='track[title]'>Title</label>
<input type='text' name='track[title]' value='<%= track.title %>'>
<br>

<label for='track[track_number]'>Track Number</label>
<input type='number' name='track[track_number]' min='0' max='100' value='<%= track.track_number %>'>
<br>


<label for='album'>Album</label>
<select name='track[album_id]'>
	<% Album.all.each do |album| %>
		<option value='<%= album.id %>' 
		<%= 'selcted' if track.persisted? && track.album_id = album.id %>>
		<%= album.title %>
		</option>
	<% end %>
</select>
<br>

<label for='buttons'>Track Type</label><br>
		<input type='radio' 
		name='track[bonus]' 
		value='true'
		<%= 'checked' if track.persisted? && track.bonus == true  %>>
		Bonus
		<input type='radio' 
		name='track[bonus]' 
		value='false'
		<%= 'checked' if track.persisted? && track.bonus == false  %>>
		Regular
<br>

<label for='track[lyrics'>Lyrics</label><br>
<textarea name='track[lyrics]' placeholder='Add some lyrics'><%= track.lyrics %>
</textarea>
<br>

<input type='submit' value='<%= text %>'>
</form>

w4d4/MusicApp/app/views/tracks/edit.html.erb
<%= render "form", track:@track %>

w4d4/MusicApp/app/views/tracks/new.html.erb
<%= render "form", track: @track %>

w4d4/MusicApp/app/views/tracks/show.html.erb
<table>
	<tr>
		<td>Title</td>
		<td><%= @track.title %></td>
	</tr>
	<tr>
		<td>Album</td>
		<td><%= @track.album.title %></td>
	</tr>
	<tr>
		<td>Type</td>
		<td><%= @track.bonus ? 'Bonus' : 'Regular' %></td>
	</tr>
	<tr>
		<td>Track Number</td>
		<td><%= @track.track_number %></td>
	</tr>
	<tr>
		<td>Lyrics</td>
		<td><pre><%=h ugly_lyrics(@track.lyrics).html_safe %></pre></td>
	</tr>
	<%= render "/notes/note" %>
	<tr>
		<td></td>
		<td><%= render "/notes/form", note: Note.new %></td>
	</tr>
</table>
<%= button_to "Delete", track_url(@track), method: :delete %>
<%= button_to "Edit", edit_track_url(@track), method: :get %>
<%= button_to "Album", album_url(@track.album_id), method: :get %>