w4d4/MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource 	:session, only: [:new, :create, :destroy]

  resources :bands do
  	resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
  		resources :tracks, only: :new
  end

  resources :tracks, except: [:new, :index] do
  	resources :notes, only: :new
  end

  resources :notes, except: [:new, :index]

end

w4d4/MusicApp/app/models/note.rb
class Note < ActiveRecord::Base
	validates :user_id, :track_id, :body, presence: true

	belongs_to(
		:track,
		class_name: 'Track',
		foreign_key: :track_id,
		primary_key: :id
	)

	belongs_to(
		:user,
		class_name: 'User',
		foreign_key: :user_id,
		primary_key: :id
	)
end

w4d4/MusicApp/app/controllers/notes_controller.rb
class NotesController < ApplicationController

	def create
		@note = Note.new(note_params)
		@note.user_id = current_user.id
		if @note.save
			redirect_to track_url(@note.track_id)
		else
			flash[:errors] = @note.errors.full_messages
			redirect_to track_url(@note.track_id)
		end
	end

	def destroy
		note = Note.find(params[:id])
		if note.user == current_user
			track_id = note.track_id
			note.destroy
			redirect_to track_url(track_id)
		else
			raise ActionController::RoutingError.new('Forbidden')
		end
	end

	protected
	def note_params
		params.require(:note).permit(:body, :track_id)
	end
end

w4d4/MusicApp/app/helpers/notes_helper.rb
module NotesHelper
end

w4d4/MusicApp/app/views/notes/_form.html.erb
<h3>Add a note</h3>
<form action='<%= notes_url %>' method='POST'>
	<input type="hidden"
       name="authenticity_token"
       value="<%= form_authenticity_token %>">
  <input type='hidden' name='note[track_id]' value='<%= @track.id %>'>
  <textarea name='note[body]'><%= note.body %></textarea>
  <input type='submit'>
</form>

w4d4/MusicApp/app/views/notes/_note.html.erb
<% @track.notes.each do |note| %>
	<tr>
		<td><%= User.find(note.user_id).email %></td>
		<td><%= note.body %></td>
		<% if current_user == note.user %>
		<td><%= button_to "Delete", note_url(note), method: :delete %></td>
		<% end %>
	</tr>
<% end %>